CREATE DATABASE healthcare;
USE healthcare;

-- PATIENT Table
CREATE TABLE PATIENT (
    PAT_NUM           CHAR(3)       PRIMARY KEY,
    INSUR_CODE        CHAR(3),
    PAT_FNAME         VARCHAR(15)   NOT NULL,
    PAT_LNAME         VARCHAR(15)   NOT NULL,
    PAT_AREACODE      CHAR(3),
    PAT_PHONE         CHAR(7),
    PAT_EMAIL         VARCHAR(50)   NOT NULL,
    PAT_BALANCE       DECIMAL(10, 2),
    FOREIGN KEY (INSUR_CODE) REFERENCES INSURANCE (INSUR_CODE)
);

-- APPOINTMENT Table
CREATE TABLE APPOINTMENT (
    APPT_NUM          CHAR(3)       PRIMARY KEY,
    APPT_DATE         DATE,
    APPT_TIME         TIME,
    APPT_SCHED        VARCHAR(50),
    PAT_NUM           CHAR(3),
    FOREIGN KEY (PAT_NUM) REFERENCES PATIENT(PAT_NUM)
);

-- DOCTOR Table
CREATE TABLE DOCTOR (
    DOC_ID            CHAR(3)       PRIMARY KEY,
    DOC_FNAME         VARCHAR(15)   NOT NULL,
    DOC_LNAME         VARCHAR(15)   NOT NULL,
    DOC_INITIAL       CHAR(1),
    DOC_EXTENSION     CHAR(4),
    DOC_OFFICE        CHAR(3)
);

-- PAT_PAYMENT Table
CREATE TABLE PAT_PAYMENT (
    PATPAY_NUM        CHAR(3)       PRIMARY KEY,
    BILL_CODE         CHAR(3),
    PATPAY_DATE       DATE,
    PATPAY_AMOUNT     DECIMAL(10, 2),
    PATPAY_TYPE       VARCHAR(20),
    PAT_NUM           CHAR(3),
    FOREIGN KEY (PAT_NUM) REFERENCES PATIENT (PAT_NUM),
    FOREIGN KEY (BILL_CODE) REFERENCES BILLING (BILL_CODE)
);

-- VISIT Table
CREATE TABLE VISIT (
    VISIT_NUM         CHAR(3)       PRIMARY KEY,
    DOC_ID            CHAR(3),
    PAT_NUM           CHAR(3),
    VISIT_DATE        DATE,
    VISIT_TIME        TIME,
    FOREIGN KEY (PAT_NUM) REFERENCES PATIENT (PAT_NUM),
    FOREIGN KEY (DOC_ID) REFERENCES DOCTOR (DOC_ID)
);

-- BILLING Table
CREATE TABLE BILLING (
    BILL_CODE         CHAR(3)       PRIMARY KEY,
    BILL_DATE         DATE,
    BILL_CHG_AMOUNT   DECIMAL(10, 2),
    BILL_PAY_AMOUNT   DECIMAL(10, 2),
    BILL_PAY_DATE     DATE,
    BILL_BALANCE      DECIMAL(10, 2),
    VISIT_NUM         CHAR(3),
    FOREIGN KEY (VISIT_NUM) REFERENCES VISIT (VISIT_NUM)
);

-- VISIT_DETAIL Table
CREATE TABLE VISIT_DETAIL (
    VISIT_NUM         CHAR(3),
    VISLINE_NUM       CHAR(3),
    VISLINE_PROBLEM   VARCHAR(255),
    VISLINE_DIAGNOSIS VARCHAR(255),
    VISLINE_CHARGE    DECIMAL(10, 2),
    PRIMARY KEY (VISIT_NUM, VISLINE_NUM),
    FOREIGN KEY (VISIT_NUM) REFERENCES VISIT (VISIT_NUM)
);

-- INSURANCE Table
CREATE TABLE INSURANCE (
    INSUR_CODE        CHAR(3)       PRIMARY KEY,
    INSUR_NAME        VARCHAR(50),
    INSUR_CONTACT     VARCHAR(50),
    INSUR_AREACODE    CHAR(3),
    INSUR_PHONE       CHAR(7),
    INSUR_EMAIL       VARCHAR(50)
);

-- INSURE_PAYMENT Table
CREATE TABLE INSURE_PAYMENT (
    INSUREPAY_NUM     CHAR(3)       PRIMARY KEY,
    INSUR_CODE        CHAR(3),
    INSUREPAY_DATE    DATE,
    BILL_CODE         CHAR(3),
    INSURE_AMOUNT     DECIMAL(10, 2),
    INSURE_PAY_TYPE   VARCHAR(20),
    FOREIGN KEY (INSUR_CODE) REFERENCES INSURANCE(INSUR_CODE),
    FOREIGN KEY (BILL_CODE) REFERENCES BILLING(BILL_CODE)
);
